import type { Metadata } from "next";
import "./globals.css";
import BottomNavBar from "./components/BottomNavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* 페이지 콘텐츠 */}
        <main>{children}</main>

        {/* BottomNavBar 컴포넌트 */}
        <BottomNavBar />
      </body>
    </html>
  );
}
